### ISSUE TITLE
Min label visible after setting *disableRange*

### ISSUE THREAD

**Issue by hernangonzalez** [WorldDownTown/RangeSeekSlider#6]
### New Issue Checklist

- [x] Updated `RangeSeekSlider` to the latest version
- [x] Checked [Gitter](https://gitter.im/WorldDownTown/RangeSeekSlider)

### Issue Description

After setting the `disableRange` to true, minLabel still shows up. I guess the following line (469):

```
        minLabel.isHidden = hideLabels
```

Should read:

```
        minLabel.isHidden = hideLabels || disableRange
```

Let me know if that's the fix or I am using it wrong and I'll send a PR.

Thank you,
H.

**Comment by WorldDownTown** [comment]
@hernangonzalez Thank you for opening the issue. I think it is probably a bug. Please send me a PR.

**Comment by hernangonzalez** [comment]
Looks like the bug has more in it. If you look at:
<img width="353" alt="screenshot 2017-04-10 11 29 00" src="https://cloud.githubusercontent.com/assets/1162963/24866619/089c40a6-1de1-11e7-9933-a8d78a0ba520.png">

I'll take a closer look and prepare a complete fix for the `disableRange` feature.

Thank you.

**Comment by hernangonzalez** [comment]
@WorldDownTown let me know if this makes sense.

The solution I found for the border there was on `updateLineHeight`:
```
        sliderLineBetweenHandles.cornerRadius = sliderLine.cornerRadius
```

Thanks.

**Comment by hernangonzalez** [comment]
Sent the PR. Might as well continue discussion there. Thank you.
