### ISSUE TITLE
Typo in ReadMe

### ISSUE THREAD

**Issue by aalenliang** [WorldDownTown/RangeSeekSlider#9]
### New Issue Checklist

- [x] Updated `RangeSeekSlider` to the latest version
- [x] Checked [Gitter](https://gitter.im/WorldDownTown/RangeSeekSlider)

### Issue Description

the example code in Carthage section:

`@IBDesignable class CustomRangeSeekSlider: RangeSeedSlider {}`

should be

`@IBDesignable class CustomRangeSeekSlider: RangeSeekSlider {}`

**Comment by WorldDownTown** [comment]
@aalenliang Thank you! I fixed it.
